MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 96264
  HEADS:
    IN_FEAT: 2048
    REDUCTION_DIM: 512
    MARGIN: 0.15
    SCALE: 30
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True