all_video_id: /mnt/workspace/public/svd/metadata-release/all-video-id
labeled_id: /mnt/workspace/public/svd/metadata-release/labeled-data-id
unlabeled_id: /mnt/workspace/public/svd/metadata-release/unlabeled-data-id
query_id: /mnt/workspace/public/svd/metadata-release/query-id
groundtruth: /mnt/workspace/public/svd/metadata-release/groundtruth
train_groundtruth: /mnt/workspace/public/svd/metadata-release/train_groundtruth
test_groundtruth: /mnt/workspace/public/svd/metadata-release/test_groundtruth

video_root_paths:
  - /mnt/workspace/public/svd/query
  - /mnt/workspace/public/svd/labeled-0
  - /mnt/workspace/public/svd/labeled-1
  - /mnt/workspace/public/svd/unlabeled-0
  - /mnt/workspace/public/svd/unlabeled-1
  - /mnt/workspace/public/svd/unlabeled-2
  - /mnt/workspace/public/svd/unlabeled-3
  - /mnt/workspace/public/svd/unlabeled-4
  - /mnt/workspace/public/svd/unlabeled-5
  - /mnt/workspace/public/svd/unlabeled-6
  - /mnt/workspace/public/svd/unlabeled-7
  - /mnt/workspace/public/svd/unlabeled-8
  - /mnt/workspace/public/svd/unlabeled-9
  - /mnt/workspace/public/svd/unlabeled-10
  - /mnt/workspace/public/svd/unlabeled-11
  - /mnt/workspace/public/svd/unlabeled-12
  - /mnt/workspace/public/svd/unlabeled-13
  - /mnt/workspace/public/svd/unlabeled-14
  - /mnt/workspace/public/svd/unlabeled-15
  - /mnt/workspace/public/svd/unlabeled-16
  - /mnt/workspace/public/svd/unlabeled-17
  - /mnt/workspace/public/svd/unlabeled-18
  - /mnt/workspace/public/svd/unlabeled-19
  - /mnt/workspace/public/svd/unlabeled-20
  - /mnt/workspace/public/svd/unlabeled-21
  - /mnt/workspace/public/svd/unlabeled-22
  - /mnt/workspace/public/svd/unlabeled-23
  - /mnt/workspace/public/svd/unlabeled-24
  - /mnt/workspace/public/svd/unlabeled-25
  - /mnt/workspace/public/svd/unlabeled-26
frame_root_path: /mnt/workspace/public/svd/frames
frame_count_file: /mnt/workspace/public/svd/num_frames
feature_root_path: /mnt/workspace/public/svd/features
